spring:
  elasticsearch:
    rest:
      uris: ${LSP_ELASTIC_SCHEME:http}://${LSP_ELASTIC_HOST:elasticsearch}:${LSP_ELASTIC_PORT:9200}
      read-timeout: 10s
      username: ${LSP_ELASTIC_USERNAME}
      password: ${LSP_ELASTIC_PASSWORD}
  datasource:
    url: jdbc:postgresql://${DB_HOST:database}:${DB_PORT:5432}/${DB_DATABASE:geo}?currentSchema=${DB_SCHEMA:pubic}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximumPoolSize: 2
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
lsp:
  geo:
    elasticsearch:
      index-name-prefix: ${LSP_ELASTIC_INDEX_NAME_PREFIX:geo}_
      default-search-radius-meters:  ${DEAULT_SEARCH_RADIUS_METERS:1000}
    dadata:
      api-debug: ${DATA_API_DEBUG:false}
      api-key: ${DATA_API_KEY}
      secrete-key: ${DATA_SECRETE_KEY}
      base-cleaner-uri: ${DATA_API_CLEANER_BASE_URI:https://cleaner.dadata.ru/api/v1}
      base-suggestions-uri: ${DATA_API_SUGGESTIONS_BASE_URI:https://suggestions.dadata.ru/suggestions/api/4_1}
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    team.lsp: DEBUG