logging:
  level:
    root: INFO
    org.springframework: TRACE
    team.lsp: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: 123
    hikari:
      maximumPoolSize: 2
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  flyway:
    schemas: public
    validate-on-migrate: false
    baseline-on-migrate: true
